// <auto-generated />
using System;
using FamilyTree.API;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FamilyTree.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20201212091435_Person_IsSpouse")]
    partial class Person_IsSpouse
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("FamilyTree.API.Model.Data.ParentChildRelationship", b =>
                {
                    b.Property<int>("RelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ChildId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ParentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RelationId");

                    b.HasIndex("ChildId")
                        .IsUnique();

                    b.HasIndex("ParentId");

                    b.ToTable("ParentChildRelationship");

                    b.HasCheckConstraint("CK_Paradox", "ParentId != ChildId");
                });

            modelBuilder.Entity("FamilyTree.API.Model.Data.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DateOfDeath")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSpouse")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastName")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("varchar(100)");

                    b.HasKey("PersonId");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("FamilyTree.API.Model.Data.SpousalRelationship", b =>
                {
                    b.Property<int>("RelationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpouseId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RelationId");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasIndex("SpouseId")
                        .IsUnique();

                    b.ToTable("SpousalRelationship");

                    b.HasCheckConstraint("CK_Monogamy", "PersonId != SpouseId");
                });

            modelBuilder.Entity("FamilyTree.API.Model.Data.ParentChildRelationship", b =>
                {
                    b.HasOne("FamilyTree.API.Model.Data.Person", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTree.API.Model.Data.Person", "Parent")
                        .WithMany("ParentChildRelationships")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FamilyTree.API.Model.Data.SpousalRelationship", b =>
                {
                    b.HasOne("FamilyTree.API.Model.Data.Person", "Person")
                        .WithOne("SpousalRelationship")
                        .HasForeignKey("FamilyTree.API.Model.Data.SpousalRelationship", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyTree.API.Model.Data.Person", "Spouse")
                        .WithMany()
                        .HasForeignKey("SpouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");

                    b.Navigation("Spouse");
                });

            modelBuilder.Entity("FamilyTree.API.Model.Data.Person", b =>
                {
                    b.Navigation("ParentChildRelationships");

                    b.Navigation("SpousalRelationship");
                });
#pragma warning restore 612, 618
        }
    }
}
